US075-AddTrailerOffer
BuurBak/BuurBak pull request #17
Opened 2022-10-18 21:16 UTC by JoJ3o

2022-10-18 21:19 UTC, JoJ3o commented
![](https://github.trello.services/images/mini-trello-icon.png) [User Story Experimenting](https://trello.com/c/6pADZYZb/130-user-story-experimenting)

2022-10-18 22:12 UTC, JoJ3o commented
![](https://github.trello.services/images/mini-trello-icon.png) [Aanhangers & aanbod toevoegen](https://trello.com/c/y3wnqTHD/75-aanhangers-aanbod-toevoegen)

2022-11-07 11:06 UTC, spark-156 requested changes

2022-11-07 11:06 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/trailers/controller/TrailerOfferController.java
> +            trailerOfferService.addTrailerOffer(createTrailerOfferDTO, authentication.getName());
return ID?

2022-11-07 11:06 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/trailers/model/TrailerOffer.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.EAGER)
```

2022-11-07 11:06 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/trailers/controller/TrailerOfferController.java
> +            trailerOfferService.addTrailerOffer(createTrailerOfferDTO, authentication.getName());
```suggestion
    public String addTrailerOffer(@Valid @RequestBody CreateTrailerOfferDTO createTrailerOfferDTO, Authentication authentication) {
        try {
            TrailerOffer trailerOffer = trailerOfferService.addTrailerOffer(createTrailerOfferDTO, authentication.getName());
            return trailerOffer.getId().toString();
```

2022-11-07 11:06 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/trailers/service/TrailerOfferService.java
> +    }
```suggestion
    public TrailerOffer addTrailerOffer(CreateTrailerOfferDTO createTrailerOfferDTO, String username) throws CustomerNotFoundException, TrailerTypeNotFoundException {
        Customer customer = customerService.findByUsername(username);
        TrailerType trailerType = trailerTypeService.findByName(createTrailerOfferDTO.trailerType());
        TrailerOffer trailerOffer = new TrailerOffer(
                trailerType,
                customer,
                createTrailerOfferDTO.length(),
                createTrailerOfferDTO.height(),
                createTrailerOfferDTO.width(),
                createTrailerOfferDTO.weight(),
                createTrailerOfferDTO.capacity(),
                createTrailerOfferDTO.licensePlateNumber(),
                createTrailerOfferDTO.pickUpTimeStart(),
                createTrailerOfferDTO.pickUpTimeEnd(),
                createTrailerOfferDTO.dropOffTimeStart(),
                createTrailerOfferDTO.dropOffTimeEnd(),
                createTrailerOfferDTO.location(),
                createTrailerOfferDTO.price(),
                createTrailerOfferDTO.available());
        trailerOfferRepository.save(trailerOffer);
        return trailerOffer;
    }
```

2022-11-07 11:17 UTC, spark-156 approved these changes

2022-11-07 11:17 UTC, merged