Removed created times from GET api request
BuurBak/BuurBak pull request #27
Opened 2022-11-08 09:28 UTC by Alyvox

2022-11-08 09:30 UTC, Alyvox commented
![](https://github.trello.services/images/mini-trello-icon.png) [Homepagina aanbod](https://trello.com/c/GH1fhIt2/9-homepagina-aanbod)

2022-11-16 12:20 UTC, Alyvox commented
Change list:
- Added unit tests for traileroffers GET API
- Added pagination for traileroffers GET API
- Made traileroffers API restful

2022-11-21 12:16 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/trailers/dto/TrailerInfoDTO.java
> +@Data
```suggestion
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
```

2022-11-21 12:18 UTC, spark-156 requested changes

2022-11-21 12:18 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/trailers/dto/TrailerTypeDTO.java
> +    public TrailerTypeDTO(String name){this.name = name;}
```suggestion
```

2022-11-21 12:18 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/trailers/dto/TrailerTypeDTO.java
> +@NoArgsConstructor
```suggestion
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
```

2022-11-21 12:23 UTC, merged