Us22 add reservation
BuurBak/BuurBak pull request #39
Opened 2022-11-25 14:51 UTC by JoJ3o

2022-12-01 11:57 UTC, spark-156 requested changes

2022-12-01 11:57 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/reservations/controller/ReservationController.java
> +    public Reservation getReservation(@PathVariable UUID id){
Should return a DTO instead of the model. What if you add sensitive information to model later but forget that you can get all that info from this endpoint?

2022-12-01 11:57 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/reservations/service/ReservationService.java
> +        Reservation reservation = new ReservationConverter().convertReservationDTOtoReservation(reservationDTO);
Why not make the ReservationConverter static so you can always call its methods instead of needing to instantiate the class

2022-12-01 11:57 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/reservations/service/ReservationService.java
> +        Reservation newReservation = new ReservationConverter().convertReservationDTOtoReservation(reservationDTO);
ditto

2022-12-01 11:57 UTC, spark-156 commented on api/src/main/java/com/buurbak/api/users/model/Customer.java
> +
```suggestion
```

2022-12-01 23:40 UTC, JoJ3o commented on api/src/main/java/com/buurbak/api/reservations/controller/ReservationController.java
> +    public Reservation getReservation(@PathVariable UUID id){
Geld dat dan ook niet voor de GET trailerOffer/:id endpoint?

2022-12-01 23:46 UTC, JoJ3o commented on api/src/main/java/com/buurbak/api/reservations/controller/ReservationController.java
> +    public Reservation getReservation(@PathVariable UUID id){
Ik neem ook aan dat je de huurder en confirmedAt wel wilt meegeven in de GET request die niet in de DTO staan maar wel in de model

2022-12-02 00:22 UTC, JoJ3o commented
![](https://github.trello.services/images/mini-trello-icon.png) [Huren knop](https://trello.com/c/o7Y2TGON/22-huren-knop)

2022-12-02 10:38 UTC, JoJ3o commented on api/src/main/java/com/buurbak/api/reservations/controller/ReservationController.java
> +    public Reservation getReservation(@PathVariable UUID id){
Created ReturnDTO for Reservation

2022-12-05 09:35 UTC, spark-156 approved these changes

2022-12-05 09:36 UTC, merged