Us018 foto toevoegen2
BuurBak/BuurBak pull request #89
Opened 2023-05-10 06:46 UTC by JoJ3o

2023-06-27 13:31 UTC, Alyvox requested changes

2023-06-27 13:31 UTC, Alyvox commented on .github/workflows/test-api.yml
> +          SPRING_PROFILES_ACTIVE: dev
Dev profiel in test omgeving???

2023-06-27 13:31 UTC, Alyvox commented on api/src/main/java/com/buurbak/api/images/controller/ImageController.java
> +//@RestController
Remove comments if there not used

2023-06-28 08:48 UTC, JoJ3o commented on .github/workflows/test-api.yml
> +          SPRING_PROFILES_ACTIVE: dev
dev environment for integration tests

2023-06-28 08:49 UTC, Alyvox approved these changes

2023-06-28 08:49 UTC, merged